# Generated by Django 5.1.1 on 2024-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheesecake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=255)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
