# Generated by Django 5.1.1 on 2024-09-16 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cheesecake_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cheesecake',
        ),
    ]
