# Generated by Django 5.1.1 on 2024-09-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_delete_cheesecake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
